import ICategoryTypes from "../../types/action-types/category.types";

export const CATEGORY_TYPES: ICategoryTypes = {
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
  TOGGLE_CATEGORIES: "TOGGLE_CATEGORIES",
};
