import IProductTypes from "../../types/action-types/product.types";

export const SHOP_TYPES: IProductTypes = {
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE",
  APPLY_FILTER: "APPLY_FILTER",
};
